back=mcr:tile/back
m1=mcr:tile/m1
m2=mcr:tile/m2
m3=mcr:tile/m3
m4=mcr:tile/m4
m5=mcr:tile/m5
m6=mcr:tile/m6
m7=mcr:tile/m7
m8=mcr:tile/m8
m9=mcr:tile/m9
s1=mcr:tile/s1
s2=mcr:tile/s2
s3=mcr:tile/s3
s4=mcr:tile/s4
s5=mcr:tile/s5
s6=mcr:tile/s6
s7=mcr:tile/s7
s8=mcr:tile/s8
s9=mcr:tile/s9
p1=mcr:tile/p1
p2=mcr:tile/p2
p3=mcr:tile/p3
p4=mcr:tile/p4
p5=mcr:tile/p5
p6=mcr:tile/p6
p7=mcr:tile/p7
p8=mcr:tile/p8
p9=mcr:tile/p9
east=mcr:tile/east
south=mcr:tile/south
west=mcr:tile/west
north=mcr:tile/north
red_dragon=mcr:tile/red_dragon
green_dragon=mcr:tile/green_dragon
white_dragon=mcr:tile/white_dragon
plum=mcr:tile/plum
orchid=mcr:tile/orchid
bamboo_flower=mcr:tile/bamboo
chrysanthemum=mcr:tile/chrysanthemum
spring=mcr:tile/spring
summer=mcr:tile/summer
autumn=mcr:tile/autumn
winter=mcr:tile/winter
