package top.ellan.mahjong.rules.mcr;

/** The 81 official MCR scoring elements, in Green Book score order. */
public enum Fan {
    DASIXI(88), DASANYUAN(88), LVYISE(88), JIULIANBAODENG(88), SIGANG(88), LIANQIDUI(88), SHISANYAO(88),
    QINGYAOJIU(64), XIAOSIXI(64), XIAOSANYUAN(64), ZIYISE(64), SIANKE(64), YISESHUANGLONGHUI(64),
    YISESITONGSHUN(48), YISESIJIEGAO(48),
    YISESIBUGAO(32), SANGANG(32), HUNYAOJIU(32),
    QIDUI(24), QIXINGBUKAO(24), QUANSHUANGKE(24), QINGYISE(24), YISESANTONGSHUN(24),
    YISESANJIEGAO(24), QUANDA(24), QUANZHONG(24), QUANXIAO(24),
    QINGLONG(16), SANSESHUANGLONGHUI(16), YISESANBUGAO(16), QUANDAIWU(16), SANTONGKE(16), SANANKE(16),
    QUANBUKAO(12), ZUHELONG(12), DAYUWU(12), XIAOYUWU(12), SANFENGKE(12),
    HUALONG(8), TUIBUDAO(8), SANSESANTONGSHUN(8), SANSESANJIEGAO(8), WUFANHU(8),
    MIAOSHOUHUICHUN(8), HAIDILAOYUE(8), GANGSHANGKAIHUA(8), QIANGGANGHU(8),
    PENGPENGHU(6), HUNYISE(6), SANSESANBUGAO(6), WUMENQI(6), QUANQIUREN(6), SHUANGANGANG(6), SHUANGJIANKE(6),
    QUANDAIYAO(4), BUQIUREN(4), SHUANGMINGGANG(4), HUJUEZHANG(4),
    JIANKE(2), QUANFENGKE(2), MENFENGKE(2), MENQIANQING(2), PINGHU(2), SIGUIYI(2),
    SHUANGTONGKE(2), SHUANGANKE(2), ANGANG(2), DUANYAO(2),
    YIBANGAO(1), XIXIANGFENG(1), LIANLIU(1), LAOSHAOFU(1), YAOJIUKE(1), MINGGANG(1),
    QUEYIMEN(1), WUZI(1), BIANZHANG(1), KANZHANG(1), DANDIAOJIANG(1), ZIMO(1), HUAPAI(1);

    private final int points;

    Fan(int points) { this.points = points; }

    public int points() { return points; }
}
